##' Fit spline model to circadian rhythm data.
##'
##' Fit spline model to circadian rhythm data.
##' @title Fit Spline
##' @param data Data object generated by buildData().
##' @param niter Number of iteration to run.
##' @param nburnin Number of burnin iterations.
##' @param nthin Thinning value used in plotting.
##' @param plotinits If TRUE then plot initial values.
##' @param verbose If TRUE then provide progess updates.
##' @return List containing MCMC output and summarized results.
##' @author Simon Bonner
##' @export
circspline <- function(data,
                       niter,
                       nburnin=NULL,
                       nthin=NULL,
                       plotinits=TRUE,
                       verbose=TRUE){
    
    ## Define paramaters for prior distributions
    priors <- priorParameters(data,verbose=verbose)
    priors$c$xi <- .001
    
    ## Define parameters for proposal distributions
    proposals <- propParameters(data,priors,verbose=verbose)

    ## Compute initial values
    inits <- parameterList$new(data,method=1,plot=plotinits,verbose=verbose)

    ## Plot actogram
    cat("  Plotting actogram with initial values...\n")
    actogram(data,double=FALSE,main="Initial Start and End Times")
    abline(h=max(data$Y)*(data$D-c(8,14,43)),col="red",lwd=1.5)
    
    ## Add initial start and end points to plot
    points(inits$s %% 24,
           (data$D-(inits$s %/% 24)-.5)*max(data$Y),
           pch=16,col="green")
    
    points(inits$e %% 24,
           (data$D-(inits$e %/% 24)-.5)*max(data$Y),
           pch=16,col="red")
    
    ## Run MCMC
    system.time(output <- mcmc(data,niter,inits,priors,proposals,model=model,verbose=verbose))
    
    ## Summarize results
    results <- circresults(output,data,niter,nburnin,nthin,verbose=verbose)

    return(list(output=output,
                results=results))
}
