##' Generate parameters for prior distributions.
##'
##' These parameters are at the highest level of the hierarchy. They
##' are fixed by the user and are not updated.
##' @title Prior Parameters
##' @param data Data object generated by buildData
##' @param verbose If TRUE then update progress
##' @return List of prior parameter values
##' @author Simon Bonner
priorParameters <- function(data,verbose){

    if(verbose)
        cat("  Setting priors...\n")

    ## Construct lists of parameters for individual priors
    list(c=list(v0=10000,V0=data$V0,V1=data$V1),
         mu.s1=list(mu=6,sigma=2),
         mu.e=list(mu=12,sigma=6),
         sigma.s=list(nu.0=1,sigma.0=.1),
         sigma.e=list(nu.0=1,sigma.0=.1),
         mu=list(shape=matrix(rep(c(3,3),data$ntreat),ncol=2,byrow=TRUE),
             rate=matrix(rep(c(20,100),data$ntreat),ncol=2,byrow=TRUE)),
         alpha=list(shape=matrix(rep(c(1,1),data$ntreat),ncol=2,byrow=TRUE),
             rate=matrix(rep(c(1,1),data$ntreat),ncol=2,byrow=TRUE)))

}
