##' Define parameters of proposal distributions.
##'
##' Define parameters of proposal distributions.
##' @title Proposal Parameters
##' @param data Data object generated by buildData
##' @param priors Prior parameters list generated with priorParameters
##' @param verbose If TRUE then update progress
##' @return List of proposal parameters
##' @author Simon Bonner
propParameters <- function(data,priors,verbose=TRUE){

    if(verbose)
        cat("  Setting parameters of proposal distributions...\n")

    Sigma <- lapply(sapply(data$Psi,ncol),function(l){
        .05 * 2.38^2/l * diag(l)
    })

    list(c=list(Sigma=Sigma),
         sigma.c=list(sigma=.5),
         alpha=list(sigma=matrix(1,nrow=length(data$treat),ncol=2)),
         mu=list(sigma=matrix(1,nrow=length(data$treat),ncol=2)),
         e=list(sigma=.1))
}
